# Generated by Django 4.2.4 on 2023-09-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0005_appuser_dob_appuser_first_name_appuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
